name: tecno_blog
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  flutter_widget_from_html: ^0.17.1
  fluttertoast: ^9.0.0
  get: ^4.7.3
  get_storage: ^2.1.1
  intl: ^0.20.2
  share_plus: ^12.0.1
  url_launcher: ^6.3.1
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

# Assets
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_text.png
    - assets/images/logo.png
    - assets/images/banners/programming.png
    - assets/images/profile_default.png
    - assets/icons/hashtag.png
    - assets/icons/pen.png
    - assets/icons/microphone.png
    - assets/icons/feather.png
    - assets/svg/tecnobot_smile.svg
    - assets/svg/tecnobot_sad.svg
    - assets/svg/arrow.svg

  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/IRANYekanXFaNum-ExtraBlack.ttf
          weight: 900
        - asset: assets/fonts/IRANYekanXFaNum-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/IRANYekanXFaNum-Bold.ttf
          weight: 700
        - asset: assets/fonts/IRANYekanXFaNum-Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANYekanXFaNum-Regular.ttf
          weight: 400
        - asset: assets/fonts/IRANYekanXFaNum-Light.ttf
          weight: 300
